# Generated by Django 4.2.1 on 2023-05-11 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_subscribe_author_alter_subscribe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='friends',
            field=models.ManyToManyField(related_name='you_friends', through='api.Subscribe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Вы'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='you_f', to=settings.AUTH_USER_MODEL, verbose_name='Ваш друг'),
        ),
    ]
